### ISSUE TITLE
How about using Project boards?

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#276]
I'd like to use [project boards](https://docs.github.com/articles/about-project-boards) to make it easy to keep track of development status.
I think we can create project boards by modules (DataStorage, MNEDC, ScoringManager etc), release name, and others (TC, Refactoring).
Please share your ideas on this.

**Comment by MoonkiHong** [comment]
This is a great idea and is well aligned with the so-called agile development. Love to follow up the Kanban style and categorize the project boards in terms of modules (with the proper labels). So +1! 😄

**Comment by suresh-lc** [comment]
Good point. Kanban board are more apt for the modules were in we work on issues.

**Comment by MoonkiHong** [comment]
Already setup as of today. Thank you @t25kim! 
- Data Storage: https://github.com/lf-edge/edge-home-orchestration-go/projects/2
- MNEDC: https://github.com/lf-edge/edge-home-orchestration-go/projects/1
- Refactoring: https://github.com/lf-edge/edge-home-orchestration-go/projects/3

**Comment by tdrozdovsky** [comment]
This is a good process for project management!
But my experience shows that for open source projects, the result is not very noticeable, since the participants in open source projects are very proactive people who work well and without the need to control.

P.S. Since the process is running, I think this issue can be closed.

**Comment by MoonkiHong** [comment]
So I close this issue. Thank you!
