### ISSUE TITLE
Comparison Analysis between Edge Computing & Cloud Computing

### ISSUE THREAD

**Issue by mchittineni** [lf-edge/edge-home-orchestration-go#366]
Can Anyone please let me know, how we can do any comparison analysis between edge computing & cloud computing with this project.

To prove that Edge Computing May or May not be better than Cloud Computing!!

Thank You in Advance!!!

**Comment by MoonkiHong** [comment]
Thank you for your kind interest in our project. 😄 Your question must be : how can we do any comparison analysis with and without a cloud computing powered by edge-home-orchestration-go (a.k.a. this project)? Since theoretically the edge computing is a dis-aggregated version of cloud computing and this project is for use cases powered by edge computing at home. Our priority is to provide the latency and data privacy at home, and this is why our project has been based on edge computing.

If you still have a question on this, we would like to recommend you to firstly watch our webinar at YouTube. https://youtu.be/ZdxNn3DrJb8

**Comment by MoonkiHong** [comment]
Since no further request, I close this issue and will follow up the similar one once we get again.
