### ISSUE TITLE
Implement CloudSync according to the new design

### ISSUE THREAD

**Issue by t25kim** [lf-edge/edge-home-orchestration-go#535]
Can we accept this raised PR as initial complete working model for CloudSync and a separate PR with the design discussed and finalised can be raised as next PR since the design changes are for all the data structure, I would suggest completing the functionality in this PR and rasing new PR for design

_Originally posted by @nitu-s-gupta in https://github.com/lf-edge/edge-home-orchestration-go/pull/532#issuecomment-1082689932_

**Comment by nitu-s-gupta** [comment]
In the Design Consideration We also need to store the client object. 
Lets consider a scenario where there are two brokers say Broker1.com, Broker2.com
Now Client1 request for Broker1.com(publish) Then Client 2 for Broker2.com(subscribe), Client 3 for Broker1.com(subscribe)
The following info would be stored in the follwoing datastructures
1. URLData<string,[]string>(url,clientid array): Since its a first time entry the url entry shall be made in URLData with clientid(client1).
PublishData<{topic,url},data>: The entry for the published data shall be made in the PublishData
2. For Next Step, Since broker2.com is not present in URLData so the entry for it is made, and connection object for the broker is created. 
SubscriptionInfo<{topic,url},[]clientid>Entry to the subscriptionInfo is also made with client id of client2
3. Now Client 3 request for again broker1.com. Now since we havent stored the client object for the Broker1.com, We cannot reuse the current homeedge object since the object is currently for connection to Broker2.com
Hence I would suggest to store clientobjects in separate hashmap mapped to urls. i.e. for every new url entry in the URLData, a entry to MQTTClient is made with url,clientobject
so In all there will be 4 Hashmaps
1. MQTTClient: <string,*Client>: Storing client object for every new url connection that homeedge makes.
2. URLData<string,[]string>: For every request publish/subscribe, If the user is not present for the url, entry to the Hashmap is made.
3. SubscriptionInfo<{topic,url},[]clientids>:For subscritpion request the client id is append for the key combination of topic,url if not present.
4.PublishData<{topic,url},data>: For every subscribed topic, entry to publish data is made with the latest data published by any client on the same url for the topic subscribed.
Plz let me know if any changes required

**Comment by t25kim** [comment]
> In the Design Consideration We also need to store the client object. Lets consider a scenario where there are two brokers say Broker1.com, Broker2.com Now Client1 request for Broker1.com(publish) Then Client 2 for Broker2.com(subscribe), Client 3 for Broker1.com(subscribe) The following info would be stored in the follwoing datastructures
> 
> 1. URLData<string,[]string>(url,clientid array): Since its a first time entry the url entry shall be made in URLData with clientid(client1).
>    PublishData<{topic,url},data>: The entry for the published data shall be made in the PublishData
> 2. For Next Step, Since broker2.com is not present in URLData so the entry for it is made, and connection object for the broker is created.
>    SubscriptionInfo<{topic,url},[]clientid>Entry to the subscriptionInfo is also made with client id of client2
> 3. Now Client 3 request for again broker1.com. Now since we havent stored the client object for the Broker1.com, We cannot reuse the current homeedge object since the object is currently for connection to Broker2.com
>    Hence I would suggest to store clientobjects in separate hashmap mapped to urls. i.e. for every new url entry in the URLData, a entry to MQTTClient is made with url,clientobject
>    so In all there will be 4 Hashmaps
> 4. MQTTClient: <string,*Client>: Storing client object for every new url connection that homeedge makes.
> 5. URLData<string,[]string>: For every request publish/subscribe, If the user is not present for the url, entry to the Hashmap is made.
> 6. SubscriptionInfo<{topic,url},[]clientids>:For subscritpion request the client id is append for the key combination of topic,url if not present.
>    4.PublishData<{topic,url},data>: For every subscribed topic, entry to publish data is made with the latest data published by any client on the same url for the topic subscribed.
>    Plz let me know if any changes required

Thanks for your idea! I agree that client objects are necessary. 
Please update the design diagram considering this [concern](https://github.com/lf-edge/edge-home-orchestration-go/pull/532#issuecomment-1081572857) share with us.

**Comment by t25kim** [comment]
Resolved by #544, #549
